DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255),
  password VARCHAR(60)
);
CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  listed BOOLEAN NOT NULL,
  created DATE NOT NULL,
  description TEXT NOT NULL,
  owner_id INT REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INT REFERENCES quizzes(id) ON DELETE CASCADE,
  question VARCHAR(510) NOT NULL
);
CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  answer TEXT NOT NULL,
  question_id INT REFERENCES questions(id) ON DELETE CASCADE,
  correct BOOLEAN
);
