DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  listed BOOLEAN NOT NULL,
  created DATE NOT NULL,
  description TEXT NOT NULL
);
CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INT REFERENCES quizzes(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL
);
CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  answer TEXT NOT NULL,
  question_id INT REFERENCES questions(id) ON DELETE CASCADE
);
